import { DataTypes } from 'sequelize';

const PaymentModel = (sequelize) => {
    const Payment = sequelize.define('Payment', {
        payment_id: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true
        },

        booking_id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'bookings',
                key: 'booking_id'
            }
        },

        amount: {
            type: DataTypes.DECIMAL(10, 2),
            allowNull: false
        },

        payment_type: {
            type: DataTypes.ENUM('FULL', 'DEPOSIT'),
            allowNull: false
        },

        pidx: {
            type: DataTypes.STRING,
            allowNull: true, // Generated by Khalti after initiation
            unique: true
        },

        transaction_id: {
            type: DataTypes.STRING,
            allowNull: true // Received after completion
        },

        status: {
            type: DataTypes.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED'),
            defaultValue: 'PENDING'
        },

        payment_method: {
            type: DataTypes.STRING,
            defaultValue: 'KHALTI'
        },

        metadata: {
            type: DataTypes.JSONB,
            allowNull: true
        }

    }, {
        tableName: 'payments',
        timestamps: true,
        underscored: true
    });

    return Payment;
};

export default PaymentModel;
